Ste flor/tiny model creator
Porthmeus/MeMoMe pull request #94
Opened 2024-03-04 13:34 UTC by SteFlor

2024-03-11 09:07 UTC, Porthmeus commented on tests/dat/e_coli_core.xml
This is part of several other tests, please add the file again to the directory, unless you fixed the other tests.

2024-03-15 08:55 UTC, Unaimend requested changes

2024-03-15 08:55 UTC, Unaimend commented on tests/dat/script_accessories/Adlercreutzia_equolifaciens_DSM_19450.xml
Please fix bulkPerformance.py accordingly because this breaks the tests

2024-03-15 08:55 UTC, Unaimend commented on tests/dat/script_accessories/e_coli_vmh.xml
Please fix bulkPerformance.py accordingly because this breaks the tests

2024-03-15 08:55 UTC, Unaimend commented on tests/dat/script_accessories/modified_model.xml
Please fix bulkPerformance.py accordingly because this breaks the tests

2024-03-19 12:32 UTC, SteFlor commented on tests/dat/script_accessories/required_excretions.txt
Explained in the parameters of the tinyModelCreator.py script

2024-03-19 12:32 UTC, SteFlor commented on tests/dat/script_accessories/desired_medium.csv
Explained in the parameters of the tinyModelCreator.py script

2024-03-19 12:33 UTC, SteFlor commented on tests/dat/script_accessories/Adlercreutzia_equolifaciens_DSM_19450.xml
fixed (moved the file to its previous path)

2024-03-19 12:33 UTC, SteFlor commented on tests/dat/script_accessories/e_coli_vmh.xml
fixed (moved the file to its previous path)

2024-03-19 12:33 UTC, SteFlor commented on tests/dat/script_accessories/modified_model.xml
fixed (moved the file to its previous path)

2024-03-19 15:45 UTC, Unaimend approved these changes

2024-03-19 15:45 UTC, merged